# Generated by Django 3.2.14 on 2022-10-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0009_auto_20221002_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prettynum',
            name='level',
            field=models.SmallIntegerField(choices=[(4, '4级'), (1, '1级'), (3, '3级'), (2, '2级')], default=1, verbose_name='级别'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='gender',
            field=models.SmallIntegerField(choices=[(2, '女'), (1, '男')], verbose_name='性别'),
        ),
    ]
