# Generated by Django 3.2.14 on 2022-10-04 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0011_auto_20221004_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prettynum',
            name='level',
            field=models.SmallIntegerField(choices=[(1, '1级'), (4, '4级'), (2, '2级'), (3, '3级')], default=1, verbose_name='级别'),
        ),
        migrations.AlterField(
            model_name='prettynum',
            name='status',
            field=models.SmallIntegerField(choices=[(2, '未占用'), (1, '已占用')], default=2, verbose_name='状态'),
        ),
    ]
