# Generated by Django 3.2.14 on 2022-10-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0012_auto_20221004_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prettynum',
            name='level',
            field=models.SmallIntegerField(choices=[(2, '2级'), (4, '4级'), (1, '1级'), (3, '3级')], default=1, verbose_name='级别'),
        ),
    ]
